### ISSUE TITLE
Gson-Bukkit serializer

### ISSUE THREAD

**Issue by cooffeeRequired** [yannicklamprecht/yannicklamprecht#1]
Hi I got a link to you but this addon doesn't seem to exist anymore, do you have something similar?

**Comment by yannicklamprecht** [comment]
No clue which addon or link you mean. Never had such thing.

**Comment by cooffeeRequired** [comment]
The "Bukkit-Gson-Serializer" library is available on GitHub at: https://github.com/YannickLamprecht/bukkit-gson-serializer

The GitHub page provides information on installing and using the library, as well as code samples for serializing and deserializing various object types.

Disclaimer: I have not tested this library, so make sure it works for your needs or that there is another library that would be better for you.

**Comment by cooffeeRequired** [comment]
![image](https://user-images.githubusercontent.com/106232282/214094055-5cbf1780-9c83-4bac-9048-ff30d9caba2e.png)
ChatGPT told me that 🗡️

**Comment by cooffeeRequired** [comment]
This is not fair... close without answer
